### ISSUE TITLE
Nomad cluster creation fails if datacenter is not dc1

### ISSUE THREAD

**Issue by Zortaniac** [jumppad-labs/jumppad#234] opened 2023-08-24 10:04 UTC
**Describe the bug**
My setup requires that the datacenter of the nomad cluster has a specific name, due to some restrictions within the job files. I noticed that as soon as I reconfigure the datacenter in the nomad cluster resource, the creation fails due to the connector not being able to be placed within the cluster.

This happens, because the connector specifically configures `datacenters = ["dc1"]` (see provider_cluster.go line 867). To solve this issue it should be enough to remove the configuration line, which lets it default to any datacenter within the cluster.

**To Reproduce**
1. Create a nomad cluster resource
2. Create a nomad client config with the entry `datacenter = "dc2"` 
3. Add `client_config` to load the nomad client config
4. Run `jumppad up`
5. See that the cluster fails to start up, due to the inability of placing the connector in the nomad cluster

**Expected behavior**
It should be possible to reconfigure the nomad datacenter without letting the cluster resource creation to fail.

**Comment by nicholasjackson** [comment] 2023-08-24 12:15
Thanks @Zortaniac I think I know what the problem is here, will have a fix out today

**Comment by nicholasjackson** [comment] 2023-08-24 19:10
Hey @Zortaniac I have pushed a fix for this to #235 

This adds a new property to the `nomad_cluster` stanza, `datacenter`

https://jumppad.dev/docs/resources/nomad/nomad_cluster

When you specify `datacenter` it will set the `datacenter` attribute in the agent config. This also ensures that the connector which is used by ingress is deployed to the correct datacenter.

**Closed** 2023-08-25 06:14 UTC
Labels: bug

**Comment by Zortaniac** [comment] 2023-08-25 07:47
Hey @nicholasjackson the fix works like a charm. Thanks!

**Comment by nicholasjackson** [comment] 2023-08-25 08:11
Glad to hear it @Zortaniac feel free to submit any issues if there are any other enhancements we can make to the Nomad cluster resource.
